module.exports = {
    incoming: [{
        key: 1,
        pinyin: 'gongzi',
        value: '工资'
    }, {
        key: 2,
        pinyin: 'hongbao',
        value: '红包'
    }, {
        key: 3,
        pinyin: 'licai',
        value: '理财'
    }, {
        key: 4,
        pinyin: 'jianzhi',
        value: '兼职'
    }, {
        key: 5,
        pinyin: 'jiangjin',
        value: '奖金'
    }, {
        key: 6,
        pinyin: 'baoxiao',
        value: '报销'
    }, {
        key: 7,
        pinyin: 'qita',
        value: '其他'
    }],
    outgoings: [{
        key: 1,
        pinyin: 'canyin',
        value: '餐饮'
    }, {
        key: 2,
        pinyin: 'gouwu',
        value: '购物'
    }, {
        key: 3,
        pinyin: 'riyong',
        value: '日用'
    }, {
        key: 4,
        pinyin: 'guoshu',
        value: '果蔬'
    }, {
        key: 5,
        pinyin: 'hongbao',
        value: '红包'
    }, {
        key: 6,
        pinyin: 'jiaotong',
        value: '交通'
    }, {
        key: 7,
        pinyin: 'zhufang',
        value: '住房'
    }, {
        key: 8,
        pinyin: 'shuji',
        value: '书籍'
    }, {
        key: 9,
        pinyin: 'yiliao',
        value: '医疗'
    }, {
        key: 10,
        pinyin: 'yule',
        value: '娱乐'
    }, {
        key: 11,
        pinyin: 'tongxun',
        value: '通讯'
    }, {
        key: 12,
        pinyin: 'fushi',
        value: '服饰'
    }, {
        key: 13,
        pinyin: 'lvxing',
        value: '旅行'
    }, {
        key: 14,
        pinyin: 'shuma',
        value: '数码'
    }, {
        key: 15,
        pinyin: 'liwu',
        value: '礼物'
    }, {
        key: 16,
        pinyin: 'qita',
        value: '其他'
    }],
    IN: 0,
    OUT: 1,
    ACCESS_TOKEN: 'fmis.access.token',
    SERVER: 'http://127.0.0.1:3000',
    RETRY_TIMES: 2,
    RETRY_DELAY: 300
}